### ISSUE TITLE
Consolidate more worker functionalities into Malloy language server

### ISSUE THREAD

**Issue by caleb-c-li** [malloydata/malloy-vscode-extension#119]
#113 sets up a way to offload Malloy semantics heavy liftings such as model building to the Malloy (vscode) language server. This issue tracks the effort to consolidate more worker functionalities into Malloy language server:
- worker's [createRunnable()](https://github.com/malloydata/malloy-vscode-extension/blob/main/src/worker/create_runnable.ts#:~:text=export%20const-,createRunnable) creates a data model, which can be done in the language server. This may apply to other `loadXYZ()` calls.
- We could pass the language server object down to worker so that we may not need to create separate message handlers, as most of the work can be performed through talking to the server.

**Comment by whscullin** [comment]
You should be able to consolidate all worker functions into the server. Basically the additional initialization logic in worker_node.ts and worker_browser.ts should be folded into server_node.ts and server_browser.ts, and then the worker can be eliminated completely.
