### ISSUE TITLE
}%all alone context breaks parser

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [malloydata/malloy-vscode-extension#19]
Currently this source file causes the malloy parser to throw an exception
```
%}
```

<img width="459" alt="image" src="https://user-images.githubusercontent.com/66150587/205511621-463382f5-417b-433d-bd86-8cb11e8756fc.png">

And "the output" is ...

```
[Error - 11:37:07 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed with message: EmptyStackException
  Code: -32603 
```

**Comment by bporterfield** [comment]
appears resolved
