### ISSUE TITLE
Webview not re-opening

### ISSUE THREAD

**Issue by sswatson** [malloydata/malloy-vscode-extension#213]
If I close the Malloy webview and try to run another query, I get error messages like `this._token.cancel is not a function` or `Webview is disposed`. The only way I know to fix the problem is reload the window.

If I'm understanding this problem correctly, it should be possible to solve it by checking whether the webview is still available and creating a new one if not. (I encountered similar behavior while developing the RelationalAI VS Code extension and solved it in that way.)

**Comment by whscullin** [comment]
I think this is fixed with https://github.com/malloydata/malloy-vscode-extension/pull/215
