### ISSUE TITLE
m4 wording changes in VSCode

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy-vscode-extension#264]
Change 'Run Query' to 'Run'  but only if @mtoy-googly-moogly  agrees
- [ ] If checked @mtoy-googly-moogly agrees
![image](https://github.com/malloydata/malloy-vscode-extension/assets/1093458/590af9f0-8466-4f7a-896d-63e3ad0cfa17)

In Schema view Change 'QUERIES' to 'VIEWS'

![image](https://github.com/malloydata/malloy-vscode-extension/assets/1093458/5b9a01f3-558a-405c-9a15-c12a9b3d8e99)

**Comment by whscullin** [comment]
Do we want to just do this across the board? Right now we uses 'Run Query' for `query:` and `run:`, and 'Run' for `sql:`
